GET /api/search/v3/search?location_id=6857&offset=0&img_req=0&q=%D0%BA%D0%BE%D0%BD%D1%8C%D1%8F%D0%BA&only_promo=0&source=cita HTTP/1.1
Host: 5d.5ka.ru
Accept-Encoding: gzip, deflate
User-Agent: okhttp/4.9.3
X-Device-Id: 9fcd5d201474437390e96d121d665e64
X-User-Store: 6857
X-Can-Receive-Push: true
X-Platform: android
X-App-Version: 4.4.0
Format: json
X-Manufacturer: unknown
X-Push-Service: GMS
X-Package-Name: ru.pyaterochka.app.browser
Connection: close

