### Каталог
GET /v2/section?showRare=1&location=218&token= HTTP/1.1
hash: f5ff97b8c46434a03e07dd8d5b964238
timestamp: 1671808923
app-version: 198
User-Agent: Dalvik/2.1.0 (Linux; U; Android 12; V2036 Build/SP1A.210812.003)
Host: api.farmlend.ru
Connection: close
Accept-Encoding: gzip, deflate

### Товары для детей и мам
GET /v2/section/7?location=218&token= HTTP/1.1
hash: af25641f2e6be4605bcf77b3b1337edf
timestamp: 1671808970
app-version: 198
User-Agent: Dalvik/2.1.0 (Linux; U; Android 12; V2036 Build/SP1A.210812.003)
Host: api.farmlend.ru
Connection: close
Accept-Encoding: gzip, deflate

### Товары детской гигиены
GET /v2/category/12?location=218&token= HTTP/1.1
hash: 8789ecf3a84e200a20a7fe2ad43bce3f
timestamp: 1671809015
app-version: 198
User-Agent: Dalvik/2.1.0 (Linux; U; Android 12; V2036 Build/SP1A.210812.003)
Host: api.farmlend.ru
Connection: close
Accept-Encoding: gzip, deflate

### Средства ухода для детей
GET /v2/subcategory-level-2/17?location=218&page=1 HTTP/1.1
hash: 8f1f70b31224cf8a390ca6263f164afb
timestamp: 1671809059
app-version: 198
User-Agent: Dalvik/2.1.0 (Linux; U; Android 12; V2036 Build/SP1A.210812.003)
Host: api.farmlend.ru
Connection: close
Accept-Encoding: gzip, deflate

### Мое солнышко (Мое солнышко) крем заживай-ка 46мл
GET /v2/product-full-info/25303?location=218 HTTP/1.1
hash: fae79d935421f0eee8b89b1aba282e74
timestamp: 1671809189
app-version: 198
User-Agent: Dalvik/2.1.0 (Linux; U; Android 12; V2036 Build/SP1A.210812.003)
Host: api.farmlend.ru
Connection: close
Accept-Encoding: gzip, deflate

### Список Фильтры в каталоге
GET /v2/filter?location=218&token=&categoryLevel=2&categoryId=17 HTTP/1.1
hash: acddc545e5ca7ab351e307657d71ee09
timestamp: 1671809499
app-version: 198
User-Agent: Dalvik/2.1.0 (Linux; U; Android 12; V2036 Build/SP1A.210812.003)
Host: api.farmlend.ru
Connection: close
Accept-Encoding: gzip, deflate

###  Отфильтрованный список
GET /v2/subcategory-level-2/17?location=218&page=1&filters[brendy][]=johnsons-baby HTTP/1.1
hash: f776d8d3082727448e493512816c191e
timestamp: 1671809877
app-version: 198
User-Agent: Dalvik/2.1.0 (Linux; U; Android 12; V2036 Build/SP1A.210812.003)
Host: api.farmlend.ru
Connection: close
Accept-Encoding: gzip, deflate

### Аптеки Москва
GET /v2/drugstore?location=218&token= HTTP/1.1
hash: ce63eb1459176fb06b33b2a5eca59e62
timestamp: 1671809945
app-version: 198
User-Agent: Dalvik/2.1.0 (Linux; U; Android 12; V2036 Build/SP1A.210812.003)
Host: api.farmlend.ru
Connection: close
Accept-Encoding: gzip, deflate

### Список регионов
GET /v2/region?token= HTTP/1.1
hash: e1aff0eff76926ddc0a0d59b49d84e90
timestamp: 1672395829
app-version: 198
User-Agent: Dalvik/2.1.0 (Linux; U; Android 6.0; Android SDK built for x86 Build/MASTER)
Host: api.farmlend.ru
Connection: close
Accept-Encoding: gzip, deflate

### города в регионе Свердловская область 7
GET /v2/region/7?token= HTTP/1.1
hash: 9ffc2d2979964c935dd7864f6b9a1a8f
timestamp: 1672395897
app-version: 198
User-Agent: Dalvik/2.1.0 (Linux; U; Android 6.0; Android SDK built for x86 Build/MASTER)
Host: api.farmlend.ru
Connection: close
Accept-Encoding: gzip, deflate

### Аптеки в городе Екб
GET /v2/drugstore?location=112&token= HTTP/1.1
hash: 76ebb2de374d5eabd545c57e6559b5c2
timestamp: 1672395955
app-version: 198
User-Agent: Dalvik/2.1.0 (Linux; U; Android 6.0; Android SDK built for x86 Build/MASTER)
Host: api.farmlend.ru
Connection: close
Accept-Encoding: gzip, deflate







